#
# VanishNoPacket
#   A fine choice of invisibility for the discerning server administrator.
#   http://www.kitteh.org
#
#  See documentation for details:
#  http://dev.bukkit.org/server-mods/vanish/pages/configuration/
#
fakeannounce:
    autofakemessages: true
    vanillamessages: true
    join: '%p joined the game.'
    quit: '%p left the game.'
hooks:
    essentials: false
    dynmap: false
permissionsupdates:
    checkonworldchange: false
effects:
    lightning:
        count: 30

permtest: false
debug: false
soundOnVanish: true
vanishedActionBarMessage: '&&3&&lYou are vanished!'
configVersionDoNotTouch: 
    SeriouslyThisWillEraseYourConfig: 7