name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VanishNoPacket
          path: target/*.jar
